### ISSUE TITLE
Question: Problems implementing a pub-sub protocol

### ISSUE THREAD

**Issue by cok666n** [xoofx/SharpNng#1]
Hi, I'm not sure if this project is maintained but here goes. 

Im tasked with implementing the client side of a pub-sub type protocol using NNG to interface with CPP applications through a C# .NET6 app. I chose SharpNng to help me with that. I can do REQ et REP type communication with no major issues, using your exemples as a base. 

I tried implementing the pub-sub according to the getting-started guides I could find : 
https://nanomsg.org/gettingstarted/nng/pubsub.html

I came up with the following :

```
internal async Task SubscribeAsync(string host, int port, string subject, DataReceivedCallback callBackFunc, CancellationToken token)
        {
            var url = $"tcp://{host}:{port}";
            int result = 0;

            Trace.WriteLine($"Sub: Starting sub socket for: {url}");

            nng_socket sock1 = default;
            try
            {
                result = nng_sub0_open(ref sock1);
                nng_assert(result);

                unsafe
                {
                    result = nng_socket_set(sock1, "NNG_OPT_SUB_SUBSCRIBE", new IntPtr(&subject), subject.Length);
                    nng_assert(result);
                }

                nng_dialer dialer = default;
                result = nng_dial(sock1, url, ref dialer, 0);
                nng_assert(result);

                Trace.WriteLine($"Sub: Dialed-in starting monitorin loop");

                while (!token.IsCancellationRequested)
                {
                    var response = this.Receive(sock1);

                    Trace.WriteLine($"Sub, response received: {response}");

                    if (callBackFunc != null)
                        callBackFunc.Invoke(response);
                }
            }
            catch (Exception e)
            {
                Trace.WriteLine($"Sub: Exception: {e}");
            }
            finally
            {
                result = nng_close(sock1);
            }

            return;
        }
```

I keep getting a NNG_ENOTSUP((9) when trying to set the NNG_OPT_SUB_SUBSCRIBE option.

I tried several things: 
- using socket_set_str instead of socket_set
- using the dialer_set methods
- setting the option before open, after open, etc
- manually adding a \0 character to my string

I've now ran out of ideas, any pointers that could help me would be appreciated. This is my first time playing with NNG so it might be something obvious I missed, but the docs did not help me so far.

Thanks,

**Comment by xoofx** [comment]
I can't tell, unfortunately, haven't used this library. I would try to test it in C++ first in case there is something wrong in the marshalling.

**Comment by cok666n** [comment]
Thanks for the reply, I didn't end up using NNG for this project, we eventually went with ZeroMQ which has a native C# port available. 

I am pretty sure my own mis-understanding of how to pass options/strings to this library is at fault here though. Maybe someone will chime in with an example of how to actually do a pub-sub protocol at some point, but this is not something I will be working on from now on. 

Thanks,
